version: '3.8'

services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile
    volumes:
      - geth-data:/usr/src/app/StratisEVM/data/
    ports:
      - "8545:8545"
      - "30303:30303"

  prysm:
    build:
      context: ./prysm
      dockerfile: Dockerfile
    volumes:
      - prysm-data:/usr/src/app/StratisEVM/data/
    ports:
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    working_dir: /usr/src/app/StratisEVM

volumes:
  geth-data:
  prysm-data: